// generate a minimal React + Vite + TS project using a wireframe and optional kit mapping

export async function generateProjectFiles(wireframe: any, kit: any): Promise<Record<string,string>>{
  const name = (wireframe?.meta?.name) || 'app-ui-designer-generated'
  const files: Record<string,string> = {}

  files['package.json'] = JSON.stringify({
    name,
    version: '0.1.0',
    private: true,
    scripts: {
      dev: 'vite',
      build: 'vite build',
      preview: 'vite preview'
    },
    dependencies: {
      react: '^18.2.0',
      'react-dom': '^18.2.0'
    },
    devDependencies: {
      vite: '^5.0.0',
      '@vitejs/plugin-react': '^4.0.0',
      typescript: '^5.1.6'
    }
  }, null, 2)

  files['index.html'] = `<!doctype html>\n<html>\n  <head>\n    <meta charset="utf-8" />\n    <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n    <title>${name}</title>\n  </head>\n  <body>\n    <div id="root"></div>\n    <script type="module" src="/src/main.tsx"></script>\n  </body>\n</html>`

  files['src/main.tsx'] = `import React from 'react'\nimport { createRoot } from 'react-dom/client'\nimport App from './App'\nimport './index.css'\n\ncreateRoot(document.getElementById('root')!).render(\n  <React.StrictMode>\n    <App />\n  </React.StrictMode>\n)`

  // simple App rendering a single page from the wireframe
  const firstText = wireframe?.pages?.[0]?.components?.[0]?.data?.label ?? 'Hello from generated app'
  files['src/App.tsx'] = `import React from 'react'\nexport default function App(){\n  return (\n    <div style={{padding:24}}>\n      <h1>${firstText}</h1>\n      <p>This project was generated by App UI Designer.</p>\n    </div>\n  )\n}`

  files['src/index.css'] = `/* Basic styles - you can replace with Tailwind in your build */\nbody{ font-family: Inter, system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial; margin:0 }`

  files['README.md'] = `# ${name}\n\nGenerated by App UI Designer.\n\nTo run locally:\n\n1. npm install\n2. npm run dev\n` 

  return files
}
